### ISSUE TITLE
Add support for named profiles

### ISSUE THREAD

**Issue by mark-greene** [akittana/aws-virtual-bastion#3]
In addition to authenticating with access keys / secrets add support for named profiles.

https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

**Comment by akittana** [comment]
Thanks for the suggestion. Since this is a web app, it can't load information from files on the system automatically. However, I can add an option in which you select your credentials file, and then the different profiles (with their auth info) would be loaded - and you can then switch between them. 

Would this work, or did you have something else in mind?

**Comment by mark-greene** [comment]
This would work.  I understand it is not straightforward with a web app.  I was thinking environment variables but I have only done this with node and go web apps and this would only work for the credentials, not the profile.

**Comment by akittana** [comment]
I just made an update that lets you load your credentials file and use the profiles configured within it to authenticate:

![image](https://user-images.githubusercontent.com/20178912/37185588-041864c2-230f-11e8-877c-385c691c7eb4.png)

I am closing this issue, but let me know if you have any issues.
